# Nmap 7.91 scan initiated Fri Mar 12 12:41:01 2021 as: nmap -sC -sV -oN nmap/broker.init -v 10.10.10.108
Nmap scan report for 10.10.10.108
Host is up (0.37s latency).
Not shown: 998 closed ports
PORT     STATE    SERVICE      VERSION
22/tcp   open     ssh          OpenSSH 7.6p1 Ubuntu 4ubuntu0.3 (Ubuntu Linux; protocol 2.0)
| ssh-hostkey: 
|   2048 4c:75:a0:7b:43:87:70:4f:70:16:d2:3c:c4:c5:a4:e9 (RSA)
|   256 f4:62:b2:ad:f8:62:a0:91:2f:0a:0e:29:1a:db:70:e4 (ECDSA)
|_  256 92:d2:87:7b:98:12:45:93:52:03:5e:9e:c7:18:71:d5 (ED25519)
4848/tcp filtered appserv-http
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel

Read data files from: /usr/bin/../share/nmap
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
# Nmap done at Fri Mar 12 12:41:53 2021 -- 1 IP address (1 host up) scanned in 51.41 seconds
